### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by goldscu** [junjie1475/spec2017-on-iOS#4]
你好：
遇到这个问题怎么处理？

 export variant\=normal
    /bin/sh -c /Users/72163106/Library/Developer/Xcode/DerivedData/Spec2017-blxvkmvisluwtddgfqgzxorcqwxw/Build/Intermediates.noindex/Spec2017.build/Debug-iphoneos/Spec2017.build/Script-B3ACD9042A0E169400B0B017.sh

cd Integer/ && \
	./init.sh # gcc workaround generate 5 copies with different symbol names
./init.sh: line 6: llvm-objcopy: command not found
./init.sh: line 6: llvm-objcopy: command not found
./init.sh: line 6: llvm-objcopy: command not found
./init.sh: line 6: llvm-objcopy: command not found
./init.sh: line 6: llvm-objcopy: command not found
duplicate symbol '_df_mark_solutions_dirty' in:
    gcc_0.o
    gcc_4.o
duplicate symbol '_df_live_set_all_dirty' in:
    gcc_0.o
    gcc_4.o

...

Showing Recent Messages
duplicate symbol '_gen_split_2000' in:

    gcc_0.o

    gcc_1.o

ld: 34800 duplicate symbols for architecture arm64

./init.sh: line 12: llvm-objcopy: command not found

make: *** [Integer/gcc.o] Error 127

Command PhaseScriptExecution failed with a nonzero exit code

Xcode: 14.3.1 
iMac: 3 GHz 六核Intel Core i5, 13.4 (22F66)
已经有 llvm-objcopy make 环境，命令行能运行

**Comment by junjie1475** [comment]
objcopy的路径是否在sh的环境变量下？

**Comment by goldscu** [comment]
下面是我在sh里的测试命令：
```
sh-3.2$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/GPAC.app/Contents/MacOS/:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/opt/llvm/bin/llvm-objcopy:/path/to/objcopy:/usr/local/opt/llvm/bin:/usr/local/opt/mongodb-community@4.4/bin:/opt/theos/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/var/bin:/var/bin
sh-3.2$ 
sh-3.2$ 
sh-3.2$ llvm-objcopy --version
llvm-objcopy, compatible with GNU objcopy
Homebrew LLVM version 16.0.6
  Optimized build.
sh-3.2$ 
```
环境变量里有llvm-objcopy了，但Xcode编译还是上面的日志报错。
我怎么判断objcopy的路径是否在sh的环境变量下，如果不在，怎么添加呢？
我是用 ```brew install llvm``` 命令安装的llvm-objcopy

**Comment by goldscu** [comment]
感谢，已经解决问题了，成功编译了。我给llvm-objcopy创建了个软链接：
`ln -s /usr/local/Cellar/llvm/16.0.6/bin/llvm-objcopy /usr/local/bin/llvm-objcopy`
